[package]
name = "neith"
version = "1.0.2"
edition = "2021"
authors = ["Xqhare"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
chrono = "0.4.35"
