[package]
name = "neith"
version = "0.4.0"
edition = "2021"
authors = ["Xqhare"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0"
